# Generated by Django 2.2.6 on 2019-11-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_index', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('formatted_address', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('place_id', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50, null=True)),
                ('rating', models.FloatField(null=True)),
                ('icon', models.CharField(max_length=40, null=True)),
                ('photo_reference', models.CharField(max_length=200, null=True)),
                ('photo_height', models.IntegerField(null=True)),
                ('photo_width', models.IntegerField(null=True)),
                ('photo_image', models.ImageField(null=True, upload_to='')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapsapi.Query')),
            ],
        ),
    ]
