# Generated by Django 2.2.6 on 2019-11-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('start_location', models.TextField()),
                ('end_location', models.TextField()),
                ('block_type', models.CharField(choices=[('CUS', 'Custom'), ('ACT', 'Activity'), ('ACM', 'Accomodation'), ('TRN', 'Transportation'), ('RST', 'Restaurant')], max_length=3)),
                ('modified', models.BooleanField(default=True)),
                ('parent_block', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_block', to='travel.TravelBlock')),
            ],
        ),
        migrations.CreateModel(
            name='TravelBlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('TravelBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelBlock')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TravelCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(height_field=500, upload_to='travel_photos/', width_field=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_TravelCommit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('day', models.DateField()),
                ('blocks', models.ManyToManyField(through='travel.TravelBlockList', to='travel.TravelBlock')),
            ],
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['last_modified_time']},
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='last_update_time',
            new_name='last_modified_time',
        ),
        migrations.AddField(
            model_name='travel',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_Travel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='collaboraters',
            field=models.ManyToManyField(blank=True, related_name='collaborater_of_Travel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel',
            name='fork_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.Travel'),
        ),
        migrations.AddField(
            model_name='travel',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_of_Travel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TravelDayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('TravelCommit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelCommit')),
                ('TravelDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelDay')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='travelcommit',
            name='days',
            field=models.ManyToManyField(through='travel.TravelDayList', to='travel.TravelDay'),
        ),
        migrations.AddField(
            model_name='travelcommit',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_of_TravelCommit', to='travel.Travel'),
        ),
        migrations.AddField(
            model_name='travelblocklist',
            name='TravelDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelDay'),
        ),
        migrations.AddField(
            model_name='travel',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_Travel', to='travel.TravelCommit'),
        ),
    ]
