# Generated by Django 2.2.6 on 2019-12-15 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
