# Generated by Django 2.2.6 on 2019-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20191126_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelday',
            name='modified',
            field=models.BooleanField(default=True),
        ),
    ]
