# Generated by Django 2.2.6 on 2019-12-04 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0006_travelday_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='collaboraters',
        ),
        migrations.AddField(
            model_name='travel',
            name='collaboroters',
            field=models.ManyToManyField(blank=True, related_name='collaborator_of_Travel', to=settings.AUTH_USER_MODEL),
        ),
    ]
