# Generated by Django 2.2.6 on 2019-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20191204_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='collaborotors',
            new_name='collaborators',
        ),
    ]
