# Generated by Django 2.2.6 on 2019-12-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20191204_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_travel', to='travel.TravelCommit'),
        ),
        migrations.AlterField(
            model_name='travelblock',
            name='end_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelcommit',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_of_TravelCommit', to='travel.Travel'),
        ),
        migrations.AlterUniqueTogether(
            name='travelblocklist',
            unique_together={('TravelDay', 'TravelBlock', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='traveldaylist',
            unique_together={('TravelCommit', 'TravelDay', 'index')},
        ),
    ]
