# Generated by Django 2.2.8 on 2019-12-13 17:46

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcommit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=travel.models.travelCommit_directory_path),
        ),
    ]
