# Generated by Django 2.2.6 on 2019-12-11 06:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', django_mysql.models.ListTextField(models.IntegerField(), size=5)),
                ('vector', django_mysql.models.ListTextField(models.IntegerField(), size=5)),
            ],
        ),
        migrations.AddField(
            model_name='travelcommit',
            name='block_dist',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[1], size=5),
        ),
        migrations.AddField(
            model_name='travelcommit',
            name='travel_embed_vector',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[1], size=512),
        ),
    ]
