# Generated by Django 2.2.6 on 2019-12-12 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0012_auto_20191211_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views_of_Travel', to=settings.AUTH_USER_MODEL),
        ),
    ]
