# Generated by Django 2.2.6 on 2019-12-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travel_views'),
        ('travel', '0012_travelcommit_photo'),
    ]

    operations = [
    ]
